### ISSUE TITLE
Planned updates for 17.10 / 18.04?

### ISSUE THREAD

**Issue by kamwoods** [stacefauske/bodhibuilder_2.2.x#9]
First off, great tool. I've been using it for a while. Future development question: I've tried BodhiBuilder 2.2.7 on 17.10 and 18.04 (current daily build as of 1/19/2018), and while both the GUI front and and ISO build work as expected, Ubiquity crashes on attempted install almost immediately after stepping through the dialogs.

I'm happy to dig into this myself, but thought I'd ask (since you appear to be the sole maintainer) - have you experimented with these versions, and do you know why this might be happening?

**Comment by stacefauske** [comment]
I haven't tested it on those versions yet at all. Since a lot can happen during alpha and beta testing (and because of my personal time commitments ), I probably won't dig into this until February. But it's definitely on the to-do list. 
If you're familiar with ubiquity, please feel free to take a look and post your findings if you like.
Thanks,
sef

**Comment by ghost** [comment]
I have the same issue on Ubuntu 18.04 bodhibuilder v2.2.7

**Comment by stacefauske** [comment]
This issue was moved to stacefauske/bodhibuilder_2.18.x_all#1

**Comment by stacefauske** [comment]
As mentioned above, I have transferred this issue to repo 'bodhibuilder_2.18.x_all'. Please reference issue # 1 there for continuation of this thread.

--- NOTE ---
Please post a relevant bodhibuilder.log file in the newly opened issue to help me out with troubleshooting. Thanks!
